### ISSUE TITLE
Condensed width value differ in variable and non variable fonts

### ISSUE THREAD

**Issue by nim-nim** [IBM/plex#296] opened 2020-01-09 20:50 UTC
Hi,

Right now the Condensed attribute has a different width meaning in variable and non variable Plex fonts. That will produce rendering artefacts when software falls back from one to the other (for coverage or availability reasons).

Please choose one canonical width for Condensed in Plex and apply it uniformly.

**Comment by BoldMonday** [comment] 2020-01-10 07:50
Please elaborate: what Condensed attribute has a different width?

**Comment by nim-nim** [comment] 2020-01-10 08:17
The condensed faces in non variable fonts have a width value of 75, probably due to the default width scale on Linux systems since 2003:
https://www.freedesktop.org/software/fontconfig/fontconfig-user.html

The condensed instances in Plex variable have a width of 85

**Comment by BoldMonday** [comment] 2020-01-10 09:47
We are not responsible for defining 75 as a width value. The Condensed fonts are 85% of the original width hence the value of 85 in the variable fonts. This is following the recommendations as described in the OpenType spec:
https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wdth

**Comment by nim-nim** [comment] 2020-01-10 11:16
What this page actually says is that the width axis allows more granularity than traditional usWidthClass, *but* that it is still correlated with usWidthClass and converting from variable width values to usWidthClass values is done by rounding (for obvious interoperability reasons).

And the usWidthClass default values are given here:
https://docs.microsoft.com/en-us/typography/opentype/spec/os2

Note those lines:

3 | Condensed | FWIDTH_CONDENSED | 75
4 | Semi-condensed | FWIDTH_SEMI_CONDENSED | 87.5

→ same values Linux systems use, they apply the OpenType spec.

Therefore: 
1. if, for design reasons, you want a reduced-width Plex variant around 85% of original width, it should not be named Condensed but SemiCondensed as that’s the default name of the closest usWidthClass  step (87.5)
2. it would also be smart to switch from 85 to 87.5 as this would align perfectly with usWidthClass defaults, 
3. as https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wdth notes otherwise rounding to this default value will occur in some cases (though 2.5% rounding is a lot less horrible than 10% rounding)

Some software will apply the spec rounding and deduce from the rounding the name to display therefore absent renaming, the faces are already rounded and named SemiCondensed in the wild (probably inkscape for example I seem to remember it was one of the apps doing this kind of font fixing)

OTOH if you really really want something apps will display as Condensed you should reduce width to 75 to conform to the usWidthClass scale in the OpenType spec.

Lastly, if you rename Condensed to SemiCondensed *but* keep a non standard 85% value (instead of 87.5) this value should also be declared in the matching non variable fonts

> The Width axis can be used as a variation axis within a variable font. It can also be used within a STAT table in non-variable fonts within a family that has width variants to provide a complete characterization of a font in relation to its family within the STAT table.

**Comment by twardoch** [comment] 2020-01-10 12:32
The condensation percentage in the usWidthClass is illustrative. 99% of "Condensed" fonts on the market don't have a 75% width of the normal fonts. 

The wdth axis spec says "The Width axis uses a scale that correlates with but is different from the scale used for the usWidthClass field of the OS/2 table." and recommends that real percentage is used. That's what Plex Variable does.

**Comment by twardoch** [comment] 2020-01-10 12:50
Also, there is nothing “standard” or “canonical” about 87.5%. Here is a spec that goes out of its depth and oversteps its intentions. Arbitrarily chosen numbers like 50 or 75 or 87.5 have no relation to reality and to how you create fonts. 

Condensed fonts don't necessarily have the same percentage difference towards normal-width fonts in all glyphs. Often the wider glyphs differ more in width than the narrow glyphs. There is no guarantee that all glyphs scale uniformly. It’s all naive assumptions of engineers, made in the early 1990s.

**Comment by nim-nim** [comment] 2020-01-10 12:51
Hi @twardoch 

You’re right that 99% of "Condensed" fonts on the market don't have a 75% width of the normal fonts. 

However, 99% of the  "Condensed" fonts on the market  don’t have system variable fonts.

When you start publishing variable fonts you need to be a lot more careful than you were for non-variable fonts, because the compatibility mechanisms defined in the OpenType spec mandate rounding of the variable axis value to the traditional usWidthClass value as an interoperability mecanisms.

This rounding means that you can not get by with nonsensical usWidthClass like you used in the past, because software will convert back and forth between it and the variable axis.

**Comment by twardoch** [comment] 2020-01-10 12:59
I believe the Plex variable fonts have different naming than the Plex static fonts — for a good reason. 

You're talking about Linux implementation from 2003. But that implementation has nothing to do with variable fonts. 

If someone today implements software that maps some ancient numerical constants to 'wdth' axis values, that person is making a grave mistake. Even if the Plex authors were to change the fonts, they're will be hundreds of variable fonts that will also not have "Condensed" at 75% and "SemiCondensed" at 87.5%. Such fonts are being created every day. 

So I suggest that you for a bug report with the developers of fontspec, because this problem will hit Linux users one way or the other. This problem should be addressed in the naive software, because the hundreds of variable fonts that are being worked on as we speak will not be changed.

**Comment by twardoch** [comment] 2020-01-10 13:03
Ps. The usWidthClass values are 1 to 9. There is nothing in the fonts about percentages, so you cannot define a “nonsensical” usWidthClass values.

**Comment by BoldMonday** [comment] 2020-01-10 13:38
The width of 85% for Plex Condensed has been established after extensive testing and careful evaluation of several widths in small decreasing steps. Therefore the resulting width has been a very deliberate choice to suit the typographical needs of the client.
After the three Condensed masters were drawn all interpolated weights were checked meticulously and any rounding errors in outlines or metrics were corrected. Already these changes will make the static Condensed fonts render slightly different than the variable font.

Changing the width to 75%, or renaming the family to Semi-Condensed, is out of the question I’m afraid.

**Comment by nim-nim** [comment] 2020-01-10 13:39
I’m talking about a Linux font management system that was initially launched in 2003 and is now the core of its text rendering (on Linux, Android, and we’re now seeing adoption on cross-platform apps). It was written by people who apply standards and specifications so no it does not use random values and the 75 value is taken directly from the OpenType spec.

> The **valid** usWidthClass values are shown in the following table. Note that **the usWidthClass values are related to but distinct from the scale for the 'wdth' axis that is used in the 'fvar' table of variable fonts** and in the STAT table. 
https://docs.microsoft.com/en-us/typography/opentype/spec/os2

>When mapping from 'wdth' values to usWidthClass, interpolate fractional values between the mapped values and then round, 
https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wdth

So fontconfig is doing exactly what the spec mandates in deriving width values from usWidthClass and converting from it to the width axis

Producing font files with broken usWidthClass values did not matter (much) when all the files were broken the same way (however, some users and software authors were sufficiently fed up with font creators laxness to rename automatically faces to the correct usWidthClass name in their GUIs).

That does not work anymore in a world of mixed variable and non variable fonts, because variable coverage is insufficient (requiring substitution) and substitution mapping relies on witdth to  usWidthClass conversions, as defined by the OpenType spec. So when, like in Plex, the Variable files use Condensed when the closest usWidthClass name is SemiCondensed, substitution breaks, because software expects to substitute a 85% width with the closest usWidthClass (SemiCondensed at 87.5), but the only thing available is Condensed (at 75%, as per the OpenType spec).

And yes the substitution will break anyway on random fonts in the wild. But we re not talking about random substitution, we are talking about substitution between Plex variable and Plex non variable (same project, released at the same time by the same people, that users can reasonably expect to be self consistent)

**Comment by twardoch** [comment] 2020-01-10 14:00
If the static Condensed fonts use OS/2.usWidthClass of 4 (not 3), there would be no problem, since the 'wdth' value of 85 clamps to 4 as per the spec. 

The naming ("Condensed", "Narrow", "Unwide", "Semi Condensed" etc.) plays no role in this. 

Basically, if variable fonts and static fonts are shipped and are supposed to be interchangable, then the choice of OS/2.usWidthClass in static fonts needs to na made based on the clamping described in the spec. 85 clamps to 4, so usWidthClass should be 4 in the statics.

**Comment by twardoch** [comment] 2020-01-10 14:03
> > When mapping from 'wdth' values to usWidthClass, **interpolate fractional values between the mapped values and then round,**
> > https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wdth
> 
> So fontconfig is doing exactly what the spec mandates in deriving width values from usWidthClass and converting from it to the 'wdth' axis

Well, no. The spec talks about going from the fine-grained 'wdth' scale to the crude usWidthClass scale, via rounding and clamping. 'wdth' 85 clamps to usWidthClass 4. 87, 87.5, 91 etc. also clamp to 4. The spec says nothing about going from usWidthClass to 'wdth'.

**Comment by nim-nim** [comment] 2020-01-10 14:25
> If the static Condensed fonts use OS/2.usWidthClass of 4 (not 3), there would be no problem, since the 'wdth' value of 85 clamps to 4 as per the spec.

Yes, that‘s on of the first things I suggested to do (modulo the discrepancy between using a 85 width value when the standard usWidthClass 4 meaning is is 87.5; I can understand it may not be worth redrawing the glyphs for such a slight difference but I doubt user testing would have changed between 85 and 87.5). 

I also wrote
> if you keep a non standard 85% value (instead of 87.5) this value should also be declared in the matching non variable fonts

 > The Width axis can be used as a variation axis within a variable font. It can also be used within a STAT table in non-variable fonts within a family that has width variants to provide a complete characterization of a font in relation to its family within the STAT table.
https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wdth

> The naming ("Condensed", "Narrow", "Unwide", "Semi Condensed" etc.) plays no role in this.

No but some software renames faces based on the usWidthClass value and then you get interop problems between software that renames and software that does not rename (a lot of document formats can be manipulated with a range of software). It’s safer to use the standard step name because the thing users get in font lists and which is saved in documents is the same regardless if the software attempts fixing the naming or not.

Generally speaking, fonts are old old tech and real world font files are a mess, so you have a huge pile of workarounds app-side. Sometimes the workarounds written to fix old font file problems cause problems in new font files because their assumptions were invalidated by OpenType additions like variable fonts. The only way to publish safe fonts that work everywhere is to adhere strictly to the text of the spec, and not trigger the workarounds in the first place.

That’s why it is technically harder to publish a font family, intended to be used with a large range of software, than publish a designer font, that will only be used in a limited set of Adobe products.

**Comment by nim-nim** [comment] 2020-01-10 14:31
@ twardoch 
> The spec says nothing about going from usWidthClass to 'wdth'.

And yet, it does

> The “% of normal” column in the following table provides a mapping from usWidthClass values 1 – 9 to 'wdth' values.
https://docs.microsoft.com/en-us/typography/opentype/spec/os2

**Comment by twardoch** [comment] 2020-01-10 14:48
> The only way to publish safe fonts that work everywhere is to adhere strictly to the text of the spec, and not trigger the workarounds in the first place.

But in this case, the text of the spec contradicts itself. On one hand it encourages font makers to use realistic percentages in 'wdth', on the other hand it implies that a “condensed” font somehow ought to have a 'wdth' axis value of 75 (at the very least in STAT).

But the spec says nothing about renaming fonts based on those values anyway. The "name" table is there to hold strings. "Condensed" is just a string, could be "Narrow" or "Less wide". 

Apps that ignore the "name" table strings and use some other fields may continue to do so, but there still is no reason to change these strings. 

The only thing I'd ensure is that static "Condensed" Plex fonts ship with OS/2.usWidthClass 4 and not 3 (I didn't check what they do now). But because static Plex fonts have been deployed for a long time now, I wouldn't necessarily advocate actually doing that change, because that may break exhisting usage scenarios. But this is something to note for the future.

Either way, the variable Plex fonts are not intended as a replacement for the static fonts. They use different naming for a reason.

**Comment by twardoch** [comment] 2020-01-10 14:54
Also — software that renames fonts based on some parameters will cause interop problems with most fonts already. There are no "standard step names” speced anywhere. The OS/2 spec uses descriptions like “Semi-condensed” but I haven't seen fonts that would use such 'name' strings. In fact, hyphens are rather discouraged in 'name' family and style names. 

The only standard names I’m aware of are "Regular", "Italic", "Bold" and "Bold Italic". For other weights, and for widths, there is no standardization. And there is a lot of real variety, regarding the actual terms, ways to abbreviate them, spaces, capitalization etc.

**Comment by twardoch** [comment] 2020-01-10 14:59
You say "The only way to publish safe fonts that work everywhere is to adhere strictly to the text of the spec, and not trigger the workarounds in the first place" — but then you suggest that 'name' strings should be changed in Plex to some non-existent “standard step names“, which are nowhere to be found in the spec. So you simultaneously recommend using workarounds and recommend not using them.

**Comment by nim-nim** [comment] 2020-01-10 15:02
> But in this case, the text of the spec contradicts itself. On one hand it encourages font makers to use realistic percentages in 'wdth', on the other hand it implies that a “condensed” font somehow ought to have a 'wdth' axis value of 75 (at the very least in STAT).

My understanding is that the spec intends for font makers to use realistic percentages in 'wdth' while staying consistent with the traditional os/2 scale:

1. if your axis value is close to a traditional os/2 step value, use this step value name (and, ideally, match its default value) → do not name something that is close to the default SemiCondensed Condensed, when Condensed is defined differently

2. if your axis value is completely different (for example, if you define a step between Normal and Medium), use a name outside the traditional scale (for example: Text)

That’s how I understand the “correlates with but is different” expression.

Also, the spec wants font makers to declare real values in STAT so they take precedence over values derived from os/2 constants when the end result differs (however, old software will make decisions based on os/2 constants only)

**Comment by twardoch** [comment] 2020-01-10 15:04
Can you point to the source of the “step value names” you keep talking about? I’m not aware of any such thing.

**Comment by nim-nim** [comment] 2020-01-10 15:05
> You say "The only way to publish safe fonts that work everywhere is to adhere strictly to the text of the spec, and not trigger the workarounds in the first place" — but then you suggest that 'name' strings should be changed in Plex to some non-existent “standard step names“, which are nowhere to be found in the spec. So you simultaneously recommend using workarounds and recommend not using them.



> You say "The only way to publish safe fonts that work everywhere is to adhere strictly to the text of the spec, and not trigger the workarounds in the first place" — but then you suggest that 'name' strings should be changed in Plex to some non-existent “standard step names“, which are nowhere to be found in the spec. 

https://docs.microsoft.com/en-us/typography/opentype/spec/os2

1 | Ultra-condensed | FWIDTH_ULTRA_CONDENSED | 50
2 | Extra-condensed | FWIDTH_EXTRA_CONDENSED | 62.5
3 | Condensed | FWIDTH_CONDENSED | 75
4 | Semi-condensed | FWIDTH_SEMI_CONDENSED | 87.5
5 | Medium (normal) | FWIDTH_NORMAL | 100
6 | Semi-expanded | FWIDTH_SEMI_EXPANDED | 112.5
7 | Expanded | FWIDTH_EXPANDED | 125
8 | Extra-expanded | FWIDTH_EXTRA_EXPANDED | 150
9 | Ultra-expanded | FWIDTH_ULTRA_EXPANDED | 200

All the os/2 steps are given a name in the spec (and then one could argue for or against the '-' in some names but that's a trivial deviation compared to others)

**Comment by twardoch** [comment] 2020-01-10 15:10
No, these are not names, these are descriptions. The very presence of the hyphens makes it obvious. The spec makes no mention of using these descriptions in the 'name' table. No doubt some software may exist that parses some strings and derives some info about the fonts from those strings, and that's clearly am app-specific workaround. But you said that it's best to not "trigger workarounds". 

If you know of a spec-compliant family that uses names like "Semi-condensed" in the 'name' table, please let me know which one that is.

**Comment by twardoch** [comment] 2020-01-10 15:13
You originally said "it should not be named Condensed but SemiCondensed as that’s the default name of the closest usWidthClass step". What's the source of this information? I don't see "SemiCondensed" anywhere in the spec.

**Comment by nim-nim** [comment] 2020-01-10 15:16
Oh, come on, don’t be ridiculous, yes that‘s not the exact name, it’s a description, real-world names usually omit the hyphen and no, it’s not outrageous to expect the SemiCondensed width to match the step with the "Semi-Condensed" description.

Real world software like inkscape will use the os/2 step names, complete with hyphens, regardless of what the font maker declared elsewhere.

**Comment by twardoch** [comment] 2020-01-10 15:17
I know that in CSS and JS, there is a standardized mechanism to go between hyphens and camelCase, but this has nothing to do with fonts. 

If you know of any software vendor that does some weird workarounds and converts between some hardcoded "Semi-condensed" and "SemiCondensed", please tell that vendor to change their code because, well, variable fonts are coming.

**Comment by twardoch** [comment] 2020-01-10 15:20
> Real world software like inkscape will use the os/2 step names, complete with hyphens, regardless of what the font maker declared elsewhere.

1. How will a change from "Condensed" to "SemiCondensed" help interop with Inkspace if it uses "Semi-condensed"? 

2. How does this relate to your recommendation against triggering app-specific workarounds? 

Sorry, I'm lost. You keep jumping between variable and static fonts, 'name' strings and some app-specific workarounds, and the spec.

**Comment by twardoch** [comment] 2020-01-10 15:24
If Inkscape saves a document referencing a font with the style name "Semi-condensed", then what are other apps supposed to do with it? They won't map that to "SemiCondensed", and if they somehow do, that's a workaround that, as you say, we should not cater to.

**Comment by nim-nim** [comment] 2020-01-10 15:28
>     1. How will a change from "Condensed" to "SemiCondensed" help interop with Inkspace if Inkspace uses "Semi-condensed"? 

That means users will see Semi-Condensed in Inkscape menus and SemiCondensed elsewhere, that will be a lot less confusing that  Semi-Condensed in Inkscape menus and Condensed elsewhere.

>     2. How does this relate to your recommendation against triggering app-specific workarounds?

The less deviations there is in real-world fonts, the easier it is to convince app authors to drop the workarounds they wrote to cope with those deviations (app authors do not especially like to write and maintain workarounds). The more font makers insist on reading specs in a way, that allows them to produce inconsistent font files, the more app authors will have to write workarounds, and interpret font files in different ways that font makers expect.

That’s the function of a spec, put everyone on the same page.

**Comment by nim-nim** [comment] 2020-01-10 15:29
> If Inkscape saves a document referencing a font with the style name "Semi-condensed", then what are other apps supposed to do with this info if they open the document?

That’s the end result of being lax when producing font files. The workarounds others write to cope with this laxness, snowball out of control.

**Comment by nim-nim** [comment] 2020-01-10 15:37
(I’m not especially happy about the Inkscape implementation, but really, read all the back and forth in this issue, all the arguments found against applying the naming and constant values clearly defined in the OpenType spec, I can understand software authors which are thoroughly fed up with font makers  and just want to be done with it)

**Comment by twardoch** [comment] 2020-01-10 15:38
> it’s not outrageous to expect the SemiCondensed width to match the step with the "Semi-Condensed" description

Perhaps — if the font has the width of exactly 87.5% of the normal. But as we’ve agreed, this is not the case for Plex, and it’s actually not the case for most fonts.  

It seems to me that you’re trying to eat the cake and keep it at the same time. 

People who expect fonts that have “Condensed” in the name to render at 75% of the text width of the normal font must be newcomers to the field. They may have just as many other false assumptions. Well, I doubt that such people exist, because that would mean they actually read the OS/2 table description in the OpenType spec. 

Most people expect a font that has the word “Condensed” to be somehow narrower than a font without that word. They have no idea about any 75%. 

Plex Variable uses a realistic value of 85 in the 'wdth' axis. Sure, the vendor could change this to 75 (but keep the glyphs as they are), which would invalidate the postulated realism of the scale. And since 85 clamps to usWidthClass 4, it _might_ be a good idea to ship the related static font with OS/2.usWidthClass 4 rather than, say, 3 (unless this change would break something sure to existing deployment). But that’s it.

**Comment by twardoch** [comment] 2020-01-10 15:48
> (I’m not especially happy about the Inkscape implementation, but really, read all the back and forth in this issue, all the arguments found against applying the naming and constant values clearly defined in the OpenType spec, I can understand software authors which are thoroughly fed up with font makers and just want to be done with it)

But there are no naming recommendations in the spec! 

Font vendors are trying hard to navigate between the spec (which is mostly ambiguous at best), and between various assumptions made by software vendors, including very bad assumptions.

Keep in mind that it's not font vendors that made the spec. The TrueType spec, the OpenType spec, the Type 1 spec, CFF etc. — that's all written by _software vendors_. Those specs are in part terrible, underdeveloped, confusing, full of historical growth. 

The software vendors who are frustrated should go vent their frustration at the right address: Apple, Microsoft, Adobe. Let the spec makers fix the specs, and the spec implementers fix their implementations — and I can guarantee that font makers would thank them all.  

Instead, you're saying “let’s change 'Condensed' to 'SemiCondensed' because the latter is more similar to 'Semi-condensed'“. Well, yes, it is more similar — but I still don’t see what this change would actually “fix”, in interop or otherwise :)

**Comment by twardoch** [comment] 2020-01-10 15:58
> That means users will see Semi-Condensed in Inkscape menus and SemiCondensed elsewhere, that will be a lot less confusing that Semi-Condensed in Inkscape menus and Condensed elsewhere.

Inkscape is opensource. Ask them to add STAT-based name parsing and actual name table parsing instead of crazy name string synthesis. 

The problem you're describing is not specific to Plex. Inkscape users see different names in Inkscape than in other apps for the **vast majority** of fonts. How will changing the naming in one font family make this better, especially Inkscape’s implementation is obviously unreasonable. 

If the Inkscape authors explicitly chose to show something different to the users for the majority of fonts, that's the decision of the Inkscape team. I don't know what the rationale was. Perhaps they wanted it to be different. If they don't, they can change. Why should this be changed in Plex? I don't get it.

**Comment by twardoch** [comment] 2020-01-10 15:59
> The more font makers insist on reading specs in a way, that allows them to produce inconsistent font files

Again: there is **nothing** in the spec that suggests that “Semi-condensed” should be a 'name' table string.

**Comment by twardoch** [comment] 2020-01-10 16:05
“Condensed” is a term that has been used in type design for a 100 years. It never meant 75%, not in the 1930s when Futura Condensed was published, not in the 1950s when Univers Condensed was published, not in the 1970s, 1980s, and not today. Thousands of font families have been designed, sometimes the “Condensed” member being 50% and sometimes 90%. Many fonts that you see today were designed in the 20th century, pre-digital. Many were made in digital, but certainly not with the idea of 75%, because that's a dumb idea.

**Comment by nim-nim** [comment] 2020-01-10 16:07
> > (I’m not especially happy about the Inkscape implementation, but really, read all the back and forth in this issue, all the arguments found against applying the naming and constant values clearly defined in the OpenType spec, I can understand software authors which are thoroughly fed up with font makers and just want to be done with it)
> 
> **But there are no naming recommendations for width-related 'name' table entries in the spec! smiley**

You’re the only one not understanding that an official name/value table in an official spec will be taken as an official recommendation by anyone writing software that uses this spec. Because there is no reason to deviate from the default table except to make software implementation harder.

> Keep in mind that it's not font vendors that made the spec. The TrueType spec, the OpenType spec, the Type 1 spec, CFF etc. — that's all written by _software vendors_. Those specs are in part terrible, underdeveloped, confusing, full of historical growth.

One reason they are terrible is that their authors try very hard to refrain from giving their actual opinion about the mess font files are (sometimes, you see them getting fed up, and writing an imperative rule, like Microsoft did with WWS; most often it’s ”this way will work fine, please follow this example” mode).

All the specs you referenced are irrelevant today except for the OpenType spec, since it’s subsumed all the rest.

>Instead, you're saying “let’s change 'Condensed' to 'SemiCondensed' in one font family because the latter is more similar to 'Semi-condensed'“. Well, yes, it is more similar — but I still don’t see what this change would actually “fix”, in interop or otherwise :)

You’re not being funny here. Go spend some time with real world users.

**Comment by nim-nim** [comment] 2020-01-10 16:14
> “Condensed” is a term that has been used in type design for a 100 years.

And how is this relevant for a new digital design like Plex?

Would *you* be happy if shopping or paying your taxes required you to master the myriad of inconsistent units that were in use the middle ages? Or would you consider the shopmaker and taxmaker to be complete *#@?

**Comment by BoldMonday** [comment] 2020-01-10 16:16
Talking about _real word:_ I’ve asked a number of times for real world examples of the interoperatibility issues that are reported by the OP. Something we can try to reproduce in order to get a sense of scale and urgency.

So far none of these examples have been provided except for hypothetical ones.

**Comment by twardoch** [comment] 2020-01-10 16:16
I have been working with real-world font users for the last 20 years or so, including 15 years of providing tech support for those who bought fonts from the world’s largest font e-commerce store. 

In those 15 years at MyFonts, I cannot recall a single incident of users complaining that the font labeled “Condensed” had a width other than 75% of the non-condensed one. 

I’m not trying to be funny. Your suggestion to change “Condensed” to “SemiCondensed” in one font family because it’s more similar (but not identical) to a description given in a technical spec addressed at software developers — I just think that suggestion does not solve anything. But it would invalidate thousands of documents already created using the Plex family in the past years.

**Comment by twardoch** [comment] 2020-01-10 16:21
> You’re the only one not understanding that an official name/value table in an official spec will be taken as an official recommendation by anyone writing software that uses this spec. Because there is no reason to deviate from the default table except to make software implementation harder.

The same spec includes the 'name' table, and clearly says that this table that ships in the font is used to store strings that should be shown in user interfaces. 

The contents of the 'name' table is messy, and so is the practice of showing font names in the UI. But if an implementer chooses to just ignore that complexity and source UI strings elsewhere — that surely isn’t the problem of the font makers who have done their best to provide good info on their fonts.

**Comment by nim-nim** [comment] 2020-01-10 16:32
> Talking about _real word:_ I’ve asked a number of times for real world examples of the interoperatibility issues that are reported by the OP. Something we can try to reproduce in order to get a sense of scale and urgency.
> 
> So far none of these examples have been provided except for hypothetical ones.

And as I wrote you before: if you don’t want to fix the problems before the files are widely disseminated, you *will* get those non hypothetical problems, and it *will* be much harder to fix anything (invalidate thousands of documents lala lala). I *will* check if something that causes early warnings is spec conformant or not, I *won’t* organise a breakage just to demonstrate software authors base their implementation on the spec.

> The same spec includes the 'name' table, and clearly says that this table that ships in the font is used to store strings that should be shown in user interfaces.

And Plex is not conformant to the WWS part of this table either (that’s another reason inkscape derives naming from os/2 constants, it produces SVG files, SVG depends on CSS, and CSS depends on strict WWS adherence)

> I have been working with real-world font users for the last 20 years or so, including 15 years of providing tech support for those who bought fonts from the world’s largest font e-commerce store.

And that is a completely different user target than the user target of OFL fonts like Plex. The OFL took up (leading to the commissioning of projects like Plex) because Myfont and others cattered to a small userbase of designers, and didn’t address the font needs of the average software user.

**Comment by BoldMonday** [comment] 2020-01-10 16:38
Plex Sans Var conforms to the WWS spec.

**Comment by nim-nim** [comment] 2020-01-10 16:40
Plex Sans Condensed does not. The whole point of WWS is to make width a face attribute

**Comment by twardoch** [comment] 2020-01-10 16:43
> And how is this relevant for a new digital design like Plex?

The main reason behind using similar terms in font naming is to make it easier for users to guess what kind of typohrahic change a certain label invokes. Choosing "Bold" should make the letters somehow heavier, choosing "Condensed" should make the letters take less horizontal space. 

But users who use different fonts also expect variety — that's the main reason they change fonts. They don't expect all bolds to look the same, all italics to look the same, all condenseds to look the same. Well, some may, but then they can just stick to one font family. 

When you design a font family, you carefully tune various visual parameters for the expected usage scenarios. Plex Sans Condensed is not extremely condensed, because that's hardly ever useful. Condensed serif faces are often even less condensed (i.e. their width varies less). On the other hand, serif italics are often much narrower than serif romans, while in sans designs the difference is mostly less pronounced. this Plex does some of these things, plus it has relatively loose letter spacing and a relatively large x-height compared to many other fonts — all for a good reason. 

Yes, there is multi-script font fallback, there are scenarios that involve dociment-wide switching from one font family to another. There, some consistency between different font families is helpful. But only as long as it doesn’t defeat the purpose of why a new font family was created in the first place. 

Developers who implement font and text support don’t face an easy task — Unicode decomposition, multi-directionality, script-specific shaping, font switching, OpenType features, various weights, widths, redundant info in font files, now color and variable fonts etc. I know how hard it is to implement good text engine support. And the dev-facing documentation isn’t great. 

But if one goes a certain idiosyncratic implementation path: deliberately ignores explicit info ('name' table strings that are in the font), and instead uses magic string synthesis based on info that isn't intended for that purpose — then, well...

**Comment by BoldMonday** [comment] 2020-01-10 16:43
As stated before: Plex Sans and Plex Sans Var are not intended to be interchangable. Hence the different naming.

**Comment by twardoch** [comment] 2020-01-10 17:07
> And that is a completely different user target than the user target of OFL fonts like Plex. The OFL took up (leading to the commissioning of projects like Plex) because Myfont and others cattered to a small userbase of designers, and didn’t address the font needs of the average software user.

Right, but the bigger problem is that software doesn't address the font needs of the average software user. The user base of fonts has grown, but software makers haven't made using fonts easier. In fact, they've managed to make using fonts more complicated (by employing hacks like that of Inkscape). 

Plex isn't made in any way less carefully than thousands of font families that existed before. The Plex team isn't deliberately trying to make the life of the user harder. In fact, Plex is an exemplary project of very careful planning, design, technical development and execution. You can hardly get any better than that. 

But working with multiligual text, with different font families, different weights and widths isn't totally “worry-free”. As a user, you need some knowledge. 

There are “dangers”, and the Plex team is taking measures to address them. Releasing Plex Sans Var with a different family name than Plex Sans is one such measure. 

If users ignore this and try to make these fonts interchangable because “they know better”, then hit a problem — that's not on the makers of Plex. If software makers ignore naming strings and come up with their own names, which leads to interop problems — that's not on the makers of Plex either. 

Trying to lead users into a false sense of stability and predictability when there is none, by force-aligning to some consistency — that would be wrong. 

The very very average software user can stick to Regular, Italic and Bold of static Plex. And I imagine that there will be no problems there. If there will be, that's a bug. 

Anyone else is not an “average software user”, and those users needs to educate themselves a bit about fonts, and manage their expectations.

**Comment by nim-nim** [comment] 2020-01-10 17:08
> > And how is this relevant for a new digital design like Plex?
> 
> The main reason behind using similar terms in font naming is to make it easier for users to guess what kind of typohrahic change a certain label invokes

> When you design a font family, you carefully tune various visual parameters for the expected usage …

None of that is antithetical to using the naming and OpenType metadata values the spec defines for something at 87.5% width.

> But if one goes a certain idiosyncratic implementation path: deliberately ignores explicit info ('name' table strings that are in the font), 

If you don’t care about software software won’t care about your naming. If you do care about software you apply the rules defined in the OpenType spec and we would not have this discussion.

> As stated before: Plex Sans and Plex Sans Var are not intended to be interchangable. Hence the different naming.

That’s irrelevant. Plex Sans Var is limited in coverage therefore it will be interchanged and Plex Sans is the obvious best source of interchange data. Interchange is not driven by font maker wishes it is driven by user coverage needs.

**Comment by BoldMonday** [comment] 2020-01-10 17:22
And interchange is always lossy and often messy.

**Comment by twardoch** [comment] 2020-01-10 17:23
**There are no rules in the OT spec** about anything being called “SemiCondensed”. Sorry, it seems to me that you’re just making this up. 

There are fonts that have strings like “Condensed” or “Cond” or “Cnd” or “Cd” or “Semicond” or “SemiCondensed” or “Semi Condensed” or “Semi Cond” or “SmCd” or “Narrow“. These fonts may have an approximate width of 87.5% or 92% or 85% or 82.65% or 77.62364% or 75% or 72.546% of the fonts that are “normal”. And this width is always approximate. The difference in width of the string “iiii” will be different from the difference in “wwww”, it will be different in Latin uppercase vs. Latin lowercase vs. digits vs. punctuation vs. other scripts. 

That’s variety in type design. That’s why new fonts are created. That's why users switch to other fonts. 

What you’re trying to suggest is that somehow this project needs to adhere to some number 87.5% that no other font family adheres to, or that users of one app that shows different names for all fonts than other apps might see a slightly more similar name in case of Plex. 

This has nothing to do about font vendors respecting software vendors. They do. Font vendors are well-aware that their products don't exist in isolation but are deployed in software environments. And the font vendors make a lot of effort to ensure consistency _where they can actually ensure it_. But there are thousands of app/OS combinations and there will always be some that misbehave.

**Comment by nim-nim** [comment] 2020-01-10 17:56
> That’s variety in type design.

Again, variety in design does not imply technical divergence at the OpenType metadata level. The first one is desirable. The second one – not.

> But there are thousands of app/OS combinations

Therefore, the only reasonable target is what the spec says instead of referencing constantly past idiosyncrasies to justify spec divergence. The defaults defined in the spec are the only thing that can drive convergence and reduce the complexity matrix.

And yes that’s a higher bar than 99% of the fonts published on Myfont or elsewhere so far. That’s the cost of getting fonts that work in generic software, and getting software that works with generic fonts.

If you can’t imagine strong spec compliance, keep to the kind of font published on MyFont. Those do not need a high level of standardisation. They do not target large scale generic deployments.

**Comment by twardoch** [comment] 2020-01-10 18:12
I can imagine strong spec compliance. As I said, for the sake of technical consistency, it’s worth ensuring (at the very least for future projects) that static fonts that ship alongside variable fonts have OS/2.usWeighClass values that are consistent with the values derived from 'wdth' axis coordinates via clamping. 

Since Plex Sans Var is separate from Plex Sans, this is not a requirement, but since the fonts _may_ be used in combination, this is something that perhaps should be coordinated. In fonts that are “strongly” intended as interchangable, this should be ensured. 

But the further changes you’re suggesting, especially changing a 'name' table string to be more similar with a descriptive name published in the spec, that’s not “strong spec compliance”, that has nothing to do with spec compliance, because those 'name' table strings have nothing to do with the descriptions found in the OS/2 table spec. Nothing in the spec says explicitly, or even implies, that these descriptions should be used as literal strings. If you’ve looked at other technical specs, they’re normally pretty clear about what is a “literal string” and what isn’t. The descriptions in the OS/2.usWidthClass spec aren’t literal strings. Wait, I think I wrote this like 10 times already, so I think it’s best for me to give it a rest.

**Comment by BoldMonday** [comment] 2020-01-10 18:23
The great thing about OFL projects is that if you want to improve it, no one will stop you from forking it and create you own improved version.

**Comment by nim-nim** [comment] 2020-01-10 18:35
> Nothing in the spec says explicitly, or even implies, that these descriptions should be used as literal strings. 

Yes, sure, it is not written explicitly (the text may lurk in a part of a spec I don't remember out of hand). However the descriptions are clearly matching specific face attributes, and it is not unreasonable for humans and app to expect that the "foo" attribute corresponds to the value with the "foo" description, and not the value with the "var" description (and, software like inkscape made this leap, to workaround the sorry state of face naming in real-wprld fonts)

> Well, even you aren’t suggesting using them as literal strings, you’re suggesting something similar. But why “SemiCondensed” for usWidthClass 4, and not “Semi Condensed”?

“Semi Condensed” gets you in all kinds of nasty corner cases where attribute ordering in face naming starts getting relevant. Space in face attributes is a terrible idea. Keep them a WWS single keyword. 

Read the [WPF font model whitepaper](https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/02/24/90/36/WPF%20Font%20Selection%20Model.pdf) if you want a description of the processing insistent face naming and whitespace in face attributes inflicts on software (that’s another pitfall Inkspace sidestepped by deriving naming from os/2 tables)

**Comment by nim-nim** [comment] 2020-01-10 18:45
> The great thing about OFL projects is that if you want to improve it, no one will stop you from forking it and create your own version.

As I wrote before, we *will* workaround all the things I report Fedora side, and you can explain to the people that commissioned the font @ IBM why one of their divisions had to workaround the project when the result hits RHEL in 5 years.

**Comment by BoldMonday** [comment] 2020-01-10 19:39
Thank you for the FUD. Good night!

**Comment by mjabbink** [comment] 2020-01-31 12:18
goodbye @nim-nim

**Closed by mjabbink** 2020-01-31 12:18 UTC
