### ISSUE TITLE
Please apply WWS naming rules strictly

### ISSUE THREAD

**Issue by nim-nim** [IBM/plex#283] opened 2019-11-09 09:02 UTC
WWS is the most recent generic naming layer in the OpenType standard (Name ID 21 and 22)
https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids

It was defined by Microsoft and Adobe after the first one tried to do smart things with modern fonts in WPF, and found out it was not possible unless fonts become more rigorous in their naming.
https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/02/24/90/36/WPF%20Font%20Selection%20Model.pdf

The default axes in variable fonts are the default WWS dimensions + optical size

Please apply this naming model strictly, applying standards is the only way to get apps to do useful things with font files.

**Comment by BoldMonday** [comment] 2019-11-09 10:43
Please provide a real-life example where Plex is misbehaving in this regard and that can be reproduced.

**Comment by nim-nim** [comment] 2019-11-09 10:57
Thanks, I seem to have an old Plex release, I'll try to check 3.0.0 now

**Comment by nim-nim** [comment] 2019-11-16 09:37
Checking 3.0.0: Condensed is still non conformant to OpenType naming rules

It should use IBM Plex Sans as Name ID 16 (with the corresponding changes in Name ID 17)
or use IBM Plex Sans as Name ID 21 (with the corresponding changes in Name ID 22)

Though going the Name ID 21/22 route will cause interop problems with software that only parses Name ID 16, so it’s much better to be conformant with WWS rules directly in Name ID 16/17

https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids
https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/02/24/90/36/WPF%20Font%20Selection%20Model.pdf
https://glyphsapp.com/tutorials/naming

Anyway if Name ID 16/17 is not conformant with OpenType WWS rules various layers of software *will* attempt to correct it (I will *definitively* correct it in Fedora Linux at the fontconfig layer, and that will trickle down to IBM’s own RHEL later). And that in turns creates interop problems with software that didn’t make the correction.

**Comment by BoldMonday** [comment] 2019-11-16 11:25
> Anyway if Name ID 16/17 is not conformant with OpenType WWS rules various layers of software _will_ attempt to correct it (I will _definitively_ correct it in Fedora Linux at the fontconfig layer, and that will trickle down to IBM’s own RHEL later). And that in turn creates interop problems with software that didn’t make the correction.

Once again: please provide a real-life example of this problem. AFAICS the difference is only about whether IBM Plex Sans Condensed is regarded as a separate family with its own entry in the font menu now. Therefore I am interested to hear about the interop problems you appear to know more about.

And please identify yourself more clearly and explain your relationship with IBM.

**Comment by nim-nim** [comment] 2019-11-16 11:51
Really, are you doing to argue about applying official OpenType specs?

Anyway, real life example
* system fixes the naming to conform to WWS rules so users get clean font lists in app menus
* user1 selects condensed in the font menu in a document-generating app
* the app writes the fixed name in the document (it does not see the original broken name, it was fixed by the system)
* user2 attempts to open the generated document on another system that didn’t perform the fix
* the other system does not find the font since it only sees knows unfixed names
→ the document is broken

**Comment by BoldMonday** [comment] 2019-11-16 11:56
No I am not arguing about specs. I am interested to solve real-life issues and not theoretical ones.

**Comment by nim-nim** [comment] 2019-11-16 12:16
A. install any Linux variant you like
B. drop
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="scan">
    <test name="family">
      <string>IBM Plex Sans</string>
    </test>
    <edit name="fontversion">
      <int>6</int>
    </edit>
  </match>
  <match target="scan">
    <test name="fullname">
      <string>IBM Plex Sans Condensed Thin Italic</string>
    </test>
    <edit name="family">
      <string>IBM Plex Sans</string>
    </edit>
    <edit name="style">
      <string>Condensed Thin Italic</string>
    </edit>
    <edit name="fontversion">
      <int>5</int>
    </edit>
  </match>
</fontconfig>
```
which is the kind of fixing the current Plex naming forces ut to do to make it behave correctly in font menus (the real conf file is much longer)

open your prefered app and write some text in "IBM Plex Sans", "Condensed Thin Italic"

save

open the same document on windows, osx, or a linux system without specifc plex fixing rules

the system won't be able to locate  "IBM Plex Sans", "Condensed Thin Italic" because what exists for it is  "IBM Plex Sans Condensed", " Thin Italic"

That's the actual end result of not applying OpenType naming specs

**Comment by BoldMonday** [comment] 2019-11-16 17:05
Thanks for the example. I see what you are trying to do here but I am not sure I understand why.

Correct me if I’m wrong but it appears you are trying to fit every font out there into the WWS model by creating your own naming conversion. But what about the thousands of existing fonts out there that do not adhere to this model? They will create the exact same interoperability problems.

As far as I understand the WWS naming system is particularly aimed at **font selection** (either through a user interface or via an algorithm). When documents are created on the WPF platform I cannot imagine that the WWS selectors are stored as the only **font identifiers**. Applications such as MS Office certainly don’t do this because it will harm interoperability with the Mac platform which does not require font naming to adhere to any system. Instead in many such cases `name ID 4 (Full font name)` is stored as font identifier, for which it is meant.

Based on the example given I argue that the problem here lies with the application in question not storing the correct font identifier(s) in the document.

Also -- if we are going to change IBM Plex Sans Condensed to the WWS naming system it will break all the documents that have been created with these fonts so far. I am not sure that is a prize worth paying.

**Comment by nim-nim** [comment] 2019-11-16 18:02
Fontconfig is the central linux place to fix broken font metadata. So it applies to all apps.

Not fixing font metadata is not an alternative as broken font metadata prevents successful font substitution (which is the main purpose of fontconfig on linux systems).

The big difference from WPF, for example, is that font renaming is done on font file scanning, not just in specific font file menus. So all apps on the system share the same font classification.

WWS is part of OpenType specs. You can delay applying all you want it will get applied someday. The more you wait to become spec conformant the more broken documents will be out there.

Which is why we make naming fixes as soon as problems are identified, so we're forward compatible against future fixed fonts, and not backwards compatible against past breakage (old names are also aliased fontconfig side, but that does not help other platforms; the primary name is the fixed one).

fontconfig also creates synthetic fonts like sans-serif, and those get saved in documents too.

**Comment by nim-nim** [comment] 2019-11-16 18:09
The Mac habit of nothing being sorted is not shared by other systems. The OpenType spec is quite thorough on the requirements of all the different OpenType naming layers, just apply the rules in the spec and you’ll be fine on all systems not just the one you’re used to.

**Comment by BoldMonday** [comment] 2019-11-16 18:13
Technically nothing broken in IBM Plex Sans now.
Both normal width and condensed families have perfect WWS style naming.
They are just defined as two individual families. Why not treat them that way in fontconfig?

**Comment by nim-nim** [comment] 2019-11-16 18:28
Because that won't be the grouping that will be done WPF-side with 
https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/02/24/90/36/WPF%20Font%20Selection%20Model.pdf

For interop reasons our metadata fixing tries to give the same results as the one Microsoft does.

The WWS parts of the OpenType spec are intended to put everyone on the same page by having a name that does not require fixing Microsoft of Linux side directly in Name ID 16/17 (or Name ID 21/22 if you insist on keeping old broken naming, but this one is less universal app-side; new fonts such as Plex should put correct values in 16/17 directly, without requiring a 21/22 patch).

**Comment by BoldMonday** [comment] 2019-11-16 20:43
This has been an interesting discussion so far, and I understand what you are trying to do.

But in order to be convinced about the interoperability issue there need to be real-life bug reports, I’m afraid. IBM has tens of thousands of people exchanging documents on both macOS and Windows platforms and nothing has been reported so far. If things are proven to be broken then that can be addressed in a future update.

**Comment by nim-nim** [comment] 2019-11-19 07:25
Well, I won't waste more time here.

The released fonts are not conformant to the OpenType spec (it does not ask just that style must be composed just of WWS attributes, it also asks that family must not contain any WWS attribute. Condensed fails the second test).

>  **Name ID 21 | WWS Family Name**. Used to provide a WWS-conformant family name in  case the entries for IDs 16 and 17 do not conform to the WWS model.  (That is, in case the entry for ID 17 includes qualifiers for some  attribute other than weight, width or slope.) If bit 8 of the  fsSelection field is set, a WWS Family Name entry should not be needed  and should not be included. Conversely, if an entry for this ID is  include, bit 8 should not be set. (See OS/2.fsSelection  field for details.) Examples of name ID 21: “Minion Pro Caption” and  “Minion Pro Display”. (Name ID 16 would be “Minion Pro” for these  examples.)

> **Name ID 22 | WWS Subfamily Name.** Used in conjunction with ID 21, this ID provides  a WWS-conformant subfamily name (reflecting only weight, width and  slope attributes) in case the entries for IDs 16 and 17 do not conform  to the WWS model. As in the case of ID 21, use of this ID should  correlate inversely with bit 8 of the fsSelection field being set.  Examples of name ID 22: “Semibold Italic”, “Bold Condensed”. (Name ID 17  could be “Semibold Italic Caption”, or “Bold Condensed Display”, for  example.)
```

The spec is pretty clear on what should be included in Name ID 16/17 *and* also provides a backwards-compatible way to fix things if past font releases were not conformant (keep Name ID 16/17 broken, make the fix in Name ID 21/22).

So, as things stand, this will require us to perform annoying and complex fixing at the fontconfig layer.

This exact kind of fixing has been known to trigger interop problems in the past with systems that didn't perform any fixing (see also Google Droid)

As noted before, Fedora Linux is the upstream for a class of IBM products, so the interop problems will happen between IBM products due to a broken IBM font.

I don't know (no one really knows) the breadth of IBM products that exist or will exist in the next years out there and how they use and will use font files. The only safe way is to be spec conformant, not hopping that every bit of software out there will silently workaround things as we'll be doing Fedora and RHEL side.

But, you can wait for things to break in production when there is not time left to fix things serenely. At this point of the issue, I don’t care about breakage in other IBM products.

**Comment by vpicone** [comment] 2020-01-31 17:09
Hey, we're going back and closing stale issues. Please feel free to reach out if you think this was closed in error!

**Closed by vpicone** 2020-01-31 17:09 UTC
