### ISSUE TITLE
npm package too big for jsDelivr

### ISSUE THREAD

**Issue by kamekku14** [IBM/plex#416] opened 2021-12-12 15:17 UTC
I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/npm/@ibm/plex) but it fails because the package is over 50 MB. Are there any files that could be removed to reduce the package size?

**Comment by jimaek** [comment] 2021-12-12 17:36
You can still load the files individually https://cdn.jsdelivr.net/gh/ibm/plex@6.0.0/IBM-Plex-Sans-Devanagari/fonts/complete/woff2/IBMPlexSansDevanagari-Bold.woff2
We just can't build the index due to the large size.

**Comment by mjabbink** [comment] 2022-02-04 05:04
FYI @vpicone

**Comment by tay1orjones** [comment] 2022-09-16 16:17
Duplicate of https://github.com/IBM/plex/issues/453

**Comment by tay1orjones** [comment] 2022-09-16 16:17
I've made an RFC to propose a fix here: https://github.com/IBM/plex/discussions/452

**Closed** 2023-03-15 12:52 UTC
