### ISSUE TITLE
Source files #609

### ISSUE THREAD

**Issue by ritaMagerDev** [IBM/plex#623] opened 2024-12-17 08:27 UTC
Hi there,

Earlier this year, the source files (ufo, glyphs, etc.) were removed from this repository due to overall file size concerns (#452, #554, #560). At the time, it was suggested that these source files would be made available as release artifacts or assets instead.

However, it doesn't seem like this practice has been implemented. Are there any plans to release the source files again? If so, where would be the best place to access or discover them?

Thank you, and I look forward to your response.

Best regards,

**Comment by BoldMonday** [comment] 2024-12-17 09:09
Duplicate of https://github.com/IBM/plex/issues/609

**Closed by BoldMonday** 2024-12-17 09:09 UTC
