### ISSUE TITLE
issue with /

### ISSUE THREAD

**Issue by aiproulx** [IBM/plex#201] opened 2018-08-30 14:52 UTC
Sharing a comment from an external customer...

Here's a screen capture (using latest Chrome on Windows 10) from a KC topic, with my highlighting:

![image1](https://user-images.githubusercontent.com/11738743/44859679-9d333d00-ac42-11e8-9bb4-59814c3f7cfe.gif)

https://www.ibm.com/support/knowledgecenter/SSEPH2_15.1.0/com.ibm.ims15.doc.sag/system_intro/ims_dbctl_over.htm

Here's a close-up ("zooming" in the browser by pressing Ctrl and +):

![image2](https://user-images.githubusercontent.com/11738743/44859684-a2908780-ac42-11e8-8d62-42115be4eadb.gif)

It's not a good look.

The solidus character (as it is known in Unicode; more colloquially, the "slash") in IBM Plex Sans needs (more) space before and after. I see the same issue when I experiment locally in my browser with IBM Plex Serif.

**Comment by BoldMonday** [comment] 2018-08-30 16:45
The problem is that this example does not use solidus (U+002F) but the fraction slash (U+2044) instead. The latter is used to compose fractions with and is designed to be combined with numerators and denominators.
<img width="676" alt="slash" src="https://user-images.githubusercontent.com/13793769/44866169-c1b00900-ac84-11e8-916f-c031048237c0.png">

**Comment by GrahamHannington** [comment] 2018-09-10 03:09
@BoldMonday,

I was that "customer" (thanks, @aiproulx).

Facepalm. You're right. I'm sorry for wasting your time (you too, @aiproulx). I could have, should have checked this. (I just have; yes, the character between "DB" and "DC" in that topic is the UTF-8-encoded byte sequence `e28184`). I've embarrassed myself.

The mystery is why the author of that topic used a fraction slash instead of a solidus. A solidus is a single-byte character; a single keystroke on a US QWERTY keyboard. You typically have to work harder to get a fraction slash. @aiproulx, if you are able to identify the IBM information developer responsible for this content, then, at your discretion, perhaps you could ask them/let them know?

Meanwhile, I'm going to crawl back under a rock and take a hard look at myself.

**Comment by GrahamHannington** [comment] 2018-09-12 02:08
I used Google to search for occurrences of the fraction slash in IBM Knowledge Center:

    ⁄ site:www.ibm.com/support/knowledgecenter

and got about 4730 results.

Some example misuses (all look bad set in IBM Plex Sans):

TCP⁄IP
C⁄C++
GDDMXD⁄MVS
⁄⁄IEWAPCOM JOB
Publish⁄Subscribe
I⁄O
input⁄output
DSIWAT⁄DSIPOS⁄DISPATCH
RACF⁄VM
Class⁄ID
Daily⁄Hourly

@aiproulx: Having established (thanks again, @BoldMonday) that this is an issue of misuse, not an issue with IBM Plex, could you (or @BoldMonday) please close this GitHub issue?

These numerous misuses in IBM Knowledge Center need investigation, but this is not the forum for that.

(Having said that, since I'm here: I wonder whether these misuses began life long ago as an IBM BookMaster symbol that was mapped—during conversion to a different markup language—to the Unicode fraction slash.)

**Closed** 2018-11-01 01:11 UTC
