### ISSUE TITLE
Questions for CJK fonts

### ISSUE THREAD

**Issue by BobH-Official** [IBM/plex#425] opened 2022-02-01 06:10 UTC
1. Will IBM Plex have a mono CJK fonts, like   [Source Han Mono](https://github.com/adobe-fonts/source-han-mono), or [Sarasa Mono/Term/Fixed](https://github.com/be5invis/Sarasa-Gothic#what-are-the-names). If does, will the Latin letters be half-width of CJK characters?(Which, like Sarasa Mono, has an advance of formatting).
2. IBM Plex JP now works weird, having a larger line height. When will it be fixed?
3. When will IBM Plex CN come out?
Thanks.😊💕

**Comment by doloopo** [comment] 2022-02-02 03:34
It's sad that the whole project hasn't been ever touched since four months ago, and the official website www.ibm.com/plex still says Japanese & Math is coming in 2021 while it has been one month of 2022...

**Comment by BoldMonday** [comment] 2022-02-14 11:06
1. At present there are no plans for mono CJK fonts.
2. Please submit bug reports as individual issues where you describe the problem in detail together with visual examples to exemplify. Also note that OTF and TTF versions of Plex Sans JP have different line heights **by design**. There is a [comment about that](https://github.com/IBM/plex/issues/388#issuecomment-890870630) by the developers from Sandoll in a different issue.
3. Plex Sans CN will be released when it has passed all checks. That might be done by this summer but nothing is certain yet.

**Closed** 2022-02-14 11:07 UTC
