### ISSUE TITLE
No ligatures available in IBM Plex Mono

### ISSUE THREAD

**Issue by Jiehong** [IBM/plex#395] opened 2021-07-28 09:49 UTC
Hi,

When using IBM Plex Mono, it would be nice to have the ability to activate some ligatures that are now commonly used when coding.

For example, many fonts provide this (such as Fira Code: https://github.com/tonsky/FiraCode), but it also comes by default in some IDEs such as Intellij with JetBrains Mono (https://www.jetbrains.com/lp/mono/#design, see section Ligature For Code).

**Comment by BoldMonday** [comment] 2021-07-28 10:58
Duplicate of #63

**Comment by Jiehong** [comment] 2021-07-29 10:59
Since #63 is closed, I'd like to add something: ligatures do not have to be enabled by default, and thus never impacting any user environment if the user does not choose to do so.

**Comment by BoldMonday** [comment] 2021-07-29 11:15
Access to OpenType features is not always available in all environments especially when it concerns non-design environments such as code editors or terminal applications. People who have developed fonts with coding ligatures agree that the recommended strategy for making such fonts is by offering essentially two versions of the fonts: one version without any coding ligatures at all, and one version with coding ligatures enabled by default.

IBM Plex Mono is currently offering one of those versions, and the other version has been debated at length in #63.

**Comment by mjabbink** [comment] 2021-07-29 18:22
I’d add ligatures are not necessary. Closing this issue.

**Closed by mjabbink** 2021-07-29 18:22 UTC
