### ISSUE TITLE
t-with-cedilla vs t-with-comma

### ISSUE THREAD

**Issue by srl295** [IBM/plex#251] opened 2019-05-03 16:20 UTC
Looking at this sample text from https://en.wikipedia.org/wiki/Laurențiu_Man :
> [Title] Laurențiu Man
> Laurenţiu Man was a Hungarian noble…

The article title uses `U+021B` which is t with comma below, and (inconsistently) the first line uses `U+0163` which is t with cedilla. In Plex Sans and Plex Serif, both characters look like a comma below. Compare to Times New Roman on a mac (light blue) which has a distinct t-with-cedilla. 

<img width="559" alt="Sin título 2asdf" src="https://user-images.githubusercontent.com/855219/57151029-c1708c00-6d84-11e9-8a3f-40fed1e2d233.png">

**Comment by srl295** [comment] 2019-05-03 16:21
![Sin título 2asdfasdf](https://user-images.githubusercontent.com/855219/57151075-e36a0e80-6d84-11e9-9bdf-ccc23099ce38.png)

**Comment by moyogo** [comment] 2019-05-03 16:30
Unfortunately, this is a common mistake.

Latin small letter t with cedilla U+0163, ţ, should look like a t with cedilla and not like a t with comma below in the Makanya language, the Manjak language, and also probably in the turkic language Gagauz since it also uses ç and ş. The same goes for the uppercase character U+0162.

**Comment by srl295** [comment] 2019-05-03 21:55
@liancu-uni

**Comment by mjabbink** [comment] 2019-06-04 20:43
In Romanian I believe the comma is correct and NOT the cedilla. But I am not an expert in Turkish.

https://en.wikipedia.org/wiki/T-comma

https://en.wikipedia.org/wiki/Romanian_alphabet


<img width="227" alt="Screen Shot 2019-06-04 at 4 41 49 PM" src="https://user-images.githubusercontent.com/32881239/58912283-b2645d00-86e7-11e9-82f5-408b6ed2b89b.png">

**Comment by fitojb** [comment] 2019-06-15 02:58
> In Romanian I believe the comma is correct and not the cedilla.

@mjabbink, Denis is talking about Makanya, Manjak and Gagauz, not Romanian. The typeface should have the correct diacritic in the correct code points, that’s why Unicode separates them, to support Romanian as well as Makanya.

**Comment by moyogo** [comment] 2019-06-15 13:17
The issue is that IBM Plex fonts are not coherent.

The cedilla characters ŞşŢţ (015E, 015F, 0162, 0163) were used in Romanian before the comma below characters ȘșȚț (0218, 0219, 021A, 021B) were added to Unicode to be specifically used in Romanian. Yet IBM Plex fonts treat Şş (015E, 015F), drawn with cedilla, differently from Ţţ (0162, 0163), drawn with comma below, as if Ţţ (0162, 0163) was still meant to be used in Romanian only.

Ţţ (0162, 0163), like Şş (015E, 015F), should be drawn with cedilla by default since are used in other languages or transcription systems that need them to have the cedilla shape. Optionally, fonts could substitute them for the comma-below characters but only in Romanian and Moldovan, in order to support older text data.

**Comment by mjabbink** [comment] 2019-06-15 13:51
I understand the situation now and we will fix

**Comment by mjabbink** [comment] 2019-06-15 13:52
@BoldMonday

**Comment by BoldMonday** [comment] 2019-06-16 09:53
@mjabbink: I will look into this.

@moyogo: Where can I find more background information about the languages in question: Makanya, Manjak and Gagauz?

**Comment by moyogo** [comment] 2019-06-19 20:02
@BoldMonday What kind of background information are you looking for?

For Gagauz, the alphabet letters were defined in Moldovan law from 1993 (http://www.legis.md/cautare/getResults?doc_id=85313&lang=ro) and amended in 1996 (http://www.legis.md/cautare/getResults?doc_id=60878&lang=ro).

For Makanya and Manjak, there are two Senegalese laws setting their alphabets and orthographic rules:
* République du Sénégal, Décret no 2005-983 relatif à l’orthographe et la séparation des mots en manjakú, 21 octobre 2005
* République du Sénégal, Décret no 2005-984 relatif à l’orthographe et la séparation des mots en mankaañ, 21 octobre 2005

**Comment by BoldMonday** [comment] 2019-06-20 07:15
@moyogo I am interested to see if those languages require other glyphs that are currently not in IBM Plex for example.

**Comment by moyogo** [comment] 2019-06-20 08:29
Makanya uses: a b c d e ë f g h i j k l m n ñ ŋ o p r s ş t ŧ ţ u w y

Manjak uses: "a b c d e ë f g h i j k l m n ñ ŋ o p r s ŝ t ţ u w y z"

**Comment by AlsoScratch** [comment] 2019-08-19 16:15
@BoldMonday @mjabbink Any time frame for when the `ţ` character might be corrected?

**Comment by mjabbink** [comment] 2019-08-20 03:50
@BoldMonday We should address this. Let’s discuss.

**Comment by AlsoScratch** [comment] 2019-09-19 07:10
> Optionally, fonts could substitute them for the comma-below characters but only in Romanian and Moldovan with the `locl` feature, in order to support older text data.

The `locl` feature is definitely something to add.

**Comment by srl295** [comment] 2020-04-30 14:58
@mjabbink @BoldMonday any update on this?

**Comment by BoldMonday** [comment] 2020-04-30 15:18
Yes. This is fixed in the upcoming versions of Plex Sans and Plex Sans Condensed. The files have been delivered to IBM.

**Comment by mjabbink** [comment] 2020-04-30 21:37
Should be released soon.

**Comment by mjabbink** [comment] 2020-06-11 04:12
I believe this is covered in the latest released

**Closed by mjabbink** 2020-06-11 04:12 UTC
Labels: type: enhancement 💡

**Comment by BoldMonday** [comment] 2020-06-11 07:10
Yes, Plex Sans and Plex Sans Condensed are fixed now.

**Comment by BoldMonday** [comment] 2021-09-29 07:17
Fixed in Plex Mono v2.3 (part of [Release v6.0.0](https://github.com/IBM/plex/releases/)).

**Comment by tay1orjones** [comment] 2022-08-16 20:05
Hey there! [v6.1.0](https://github.com/IBM/plex/releases/tag/v6.1.0) was just released that references this issue. 

Comment here or join the [release discussion](https://github.com/IBM/plex/discussions/468) to provide feedback or voice concerns. Thanks!

**Comment by tay1orjones** [comment] 2023-05-08 16:41
Hey there! [v6.3.0](https://github.com/IBM/plex/releases/tag/v6.3.0) was just released that references this issue.

Comment here or join the [release discussion](https://github.com/IBM/plex/discussions/520) to provide feedback or voice concerns. Thanks!
