### ISSUE TITLE
ff, ffi, ffl ligatures

### ISSUE THREAD

**Issue by Cogli** [IBM/plex#619] opened 2024-12-10 16:25 UTC
Hi,

In italian the sequences "ffi" and "ffl" are pretty common. Though is perfectly fine not to have any ligature at all, is instead very distracting to have a fi or fl ligature in the middle of the aformentioned sequences: that which is a unique phoneme ends up being divided in two arbitrary parts.

In Plex Math, ff, ffi, ffl ligatures are already there. Maybe they can be implemented in the other fonts as well.

Thank you!

**Comment by BoldMonday** [comment] 2024-12-10 20:07
Duplicate of https://github.com/IBM/plex/issues/611

**Closed by BoldMonday** 2024-12-10 20:07 UTC
