### ISSUE TITLE
Small letter "i" is override

### ISSUE THREAD

**Issue by HARIPRASADHARI** [IBM/plex#164] opened 2018-04-26 11:42 UTC
Please check the screenshot
![letter_i](https://user-images.githubusercontent.com/10670604/39303752-fcbf8b6a-4974-11e8-861f-48033b394d9c.png)

**Comment by BoldMonday** [comment] 2018-04-26 12:27
Please elaborate what the issue is. It is not clear from the screenshot nor the subject.

**Comment by HARIPRASADHARI** [comment] 2018-04-26 12:56
Check the letters "f" and "i" is collapsed in the word profile.
That dev toolbar shows: am using IBM plex google font link.

**Comment by BoldMonday** [comment] 2018-04-26 13:04
That is a common Latin `fi` ligature. It is a typographical refinement.

**Comment by HARIPRASADHARI** [comment] 2018-04-26 13:06
is there any solution?

**Comment by seejamescode** [comment] 2018-04-26 13:41
You can wrap the two letters in a `<span>fi</span>` and then increase `letter-spacing` on the span. However, since this is the intended outcome we will close the issue.

**Closed by seejamescode** 2018-04-26 13:41 UTC

**Comment by BoldMonday** [comment] 2018-04-26 13:44
There are ways to disable ligatures in css. But I am not a css expert.
